/*eslint-disable */

export default {
  // API_URL: 'http://shipping.ap-south-1.elasticbeanstalk.com/api/v1/',
  // API_URL:
  //  window.location.hostname === 'localhost'
  //    ? 'http://localhost:9000/api/v1/'
  //    : 'https://shipping.tatwaglobal.com/api/v1/',
  API_URL: 'https://shipping.tatwaglobal.com/api/v1/',
  DOTNET_API_URL:'https://shipping-dotnet.tatwaglobal.com/',
  // API_URL: 'http://localhost:9000/api/v1/',
  METHOD: {
    POST: 'POST',
    GET: 'GET',
    PUT: 'PUT',
    DELETE: 'DELETE',
  },
  HEADER: {
    Accept: 'application/json',
    'Content-Type': 'application/json',
  },
  FETCH_GROUPS: 'group/getAllGroup',
  ADD_GROUP: 'group/addGroup',
  UPDATE_GROUP: 'group/updateGroup/',
  DELETE_GROUP: 'group/deleteGroup/',
  ADD_USER: 'user/register',
  FETCH_USERS: 'user/getAllUser',
  FETCH_MODULES: 'module/getAllModule',
  FETCH_MODULETREE: 'module/listModuleSubModule',
  FETCH_MODULEBYTYPE: 'module/getAllModulesByType?moduleType=',
  ADD_MODULE: 'module/addModule',
  UPDATE_MODULE: 'module/updateModule/',
  DELETE_MODULE: 'module/deleteModule/',
  ADD_CHARTER_PARTY: 'chaterParty/addChaterPartyForm',
  FETCH_CHARTER_PARTY: 'chaterParty/getAllChaterPartyForm',
  UPDATE_CHARTER_PARTY: 'chaterParty/updateChaterPartyForm/',
  DELETE_CHARTER_PARTY: 'chaterParty/deleteChaterPartyForm/',
  ADD_ORGANISATION: 'organisation/addOrganisation',
  FETCH_ORGANISATION: 'organisation/getAllOrganisation',
  UPDATE_ORGANISATION: 'organisation/updateOrganisation/',
  DELETE_ORGANISATION: 'organisation/deleteOrganisation/',
  ADD_COUNTRY: 'country/addCountry',
  FETCH_COUNTRY: 'country/getAllCountry',
  UPDATE_COUNTRY: 'country/updateCountry/',
  DELETE_COUNTRY: 'country/deleteCountry/',
  ADD_STATE: 'state/addState',
  UPDATE_STATE: 'state/updateState/',
  FETCH_STATE: 'state/getAllState',
  FETCH_STATE_BY_COUNTRY_ID: 'state/getStateByCountryId/',
  DELETE_STATE: 'state/deleteState/',
  FETCH_DISTRIBUTION_LIST: 'distributionList/getAllDistributionList',
  ADD_DISTRIBUTION_LIST: 'distributionList/addDistributionList',
  UPDATE_DISTRIBUTION_LIST: 'distributionList/updateDistributionList/',
  DELETE_DISTRIBUTION_LIST: 'distributionList/deleteDistributionList/',

  FETCH_Extra_Freight_Terms: 'extraFreightTerms/getAllExtraFreightTerms',
  ADD_Extra_Freight_Terms: 'extraFreightTerms/addExtraFreightTerms',
  UPDATE_Extra_Freight_Terms: 'extraFreightTerms/updateExtraFreightTerms/',
  DELETE_Extra_Freight_Terms: 'extraFreightTerms/deleteExtraFreightTerms/',

  FETCH_LAYTIME_COMMENCE: 'laytimeToCommenceTerms/getAllLaytimeToCommenceTerms',
  ADD_LAYTIME_COMMENCE: 'laytimeToCommenceTerms/addLaytimeToCommenceTerms',
  UPDATE_LAYTIME_COMMENCE: 'laytimeToCommenceTerms/updateLaytimeToCommenceTerms/',
  DELETE_LAYTIME_COMMENCE: 'laytimeToCommenceTerms/deleteLaytimeToCommenceTerms/',

  FETCH_LAYTIME_TYPE: 'laytimeType/getAllLaytimeType',
  ADD_LAYTIME_TYPE: 'laytimeType/addLaytimeType',
  UPDATE_LAYTIME_TYPE: 'laytimeType/updateLaytimeType/',
  DELETE_LAYTIME_TYPE: 'laytimeType/deleteLaytimeType/',

  FETCH_LOADING_COST: 'loadingCostTerms/getAllLoadingCostTerms',
  ADD_LOADING_COST: 'loadingCostTerms/addLoadingCostTerms',
  UPDATE_LOADING_COST: 'loadingCostTerms/updateLoadingCostTerms/',
  DELETE_LOADING_COST: 'loadingCostTerms/deleteLoadingCostTerms/',

  FETCH_LAYTIME_TERMS: 'laytimeTerms/getAllLaytimeTerms',
  ADD_LAYTIME_TERMS: 'laytimeTerms/addLaytimeTerms',
  UPDATE_LAYTIME_TERMS: 'laytimeTerms/updateLaytimeTerms/',
  DELETE_LAYTIME_TERMS: 'laytimeTerms/deleteLaytimeTerms/',
  FETCH_NOR_TO_TENDER: 'norToTenderTerms/getAllNORToTenderTerms',
  ADD_NOR_TO_TENDER: 'norToTenderTerms/addNORToTenderTerms',
  UPDATE_NOR_TO_TENDER: 'norToTenderTerms/updateNORToTenderTerms/',
  DELETE_NOR_TO_TENDER: 'norToTenderTerms/deleteNORToTenderTerms/',
  FETCH_OTHER_LOADING_TERMS: 'otherLoadingTerms/getAllOtherLoadingTerms',
  ADD_OTHER_LOADING_TERMS: 'otherLoadingTerms/addOtherLoadingTerms',
  UPDATE_OTHER_LOADING_TERMS: 'otherLoadingTerms/updateOtherLoadingTerms/',
  DELETE_OTHER_LOADING_TERMS: 'otherLoadingTerms/deleteOtherLoadingTerms/',
  FETCH_PAYMENT_TERMS: 'paymentTerms/getAllPaymentTerms',
  ADD_PAYMENT_TERMS: 'paymentTerms/addPaymentTerms',
  UPDATE_PAYMENT_TERMS: 'paymentTerms/updatePaymentTerms/',
  DELETE_PAYMENT_TERMS: 'paymentTerms/deletePaymentTerms/',

  FETCH_PRICING_TEMPLATE: 'pricingTemplate/getAllPricingTemplate',
  ADD_PRICING_TEMPLATE: 'pricingTemplate/addPricingTemplate',
  UPDATE_PRICING_TEMPLATE: 'pricingTemplate/updatePricingTemplate/',
  DELETE_PRICING_TEMPLATE: 'pricingTemplate/deletePricingTemplate/',
  FETCH_PRICING_TEMPLATE_RULES: 'pricingTemplateRule/getAllPricingTemplateRule',
  ADD_PRICING_TEMPLATE_RULES: 'pricingTemplateRule/addPricingTemplateRule',
  UPDATE_PRICING_TEMPLATE_RULES: 'pricingTemplateRule/updatePricingTemplateRule/',
  DELETE_PRICING_TEMPLATE_RULES: 'pricingTemplateRule/deletePricingTemplateRule/',
  FETCH_QUANTITY_DESC: 'quantityDescriptionTerms/getAllQuantityDescriptionTerms',
  ADD_QUANTITY_DESC: 'quantityDescriptionTerms/addQuantityDescriptionTerms',
  UPDATE_QUANTITY_DESC: 'quantityDescriptionTerms/updateQuantityDescriptionTerms/',
  DELETE_QUANTITY_DESC: 'quantityDescriptionTerms/deleteQuantityDescriptionTerms/',
  FETCH_SHIFTING_TERM: 'shiftingTerms/getAllShiftingTerms',
  ADD_SHIFTING_TERM: 'shiftingTerms/addShiftingTerms',
  UPDATE_SHIFTING_TERM: 'shiftingTerms/updateShiftingTerms/',
  DELETE_SHIFTING_TERM: 'shiftingTerms/deleteShiftingTerms/',

  FETCH_STANDARD_PARAGRAPH: 'standardPargraph/getAllStandardPargraph',
  ADD_STANDARD_PARAGRAPH: 'standardPargraph/addstandardPargraph',
  UPDATE_STANDARD_PARAGRAPH: 'standardPargraph/updatestandardPargraph/',
  DELETE_STANDARD_PARAGRAPH: 'standardPargraph/deletestandardPargraph/',

  FETCH_TIME_TO_TENDER: 'timeToTender/getAlltimeToTender',
  ADD_TIME_TO_TENDER: 'timeToTender/addTimeToTender',
  UPDATE_TIME_TO_TENDER: 'timeToTender/updateTimeToTender/',
  DELETE_TIME_TO_TENDER: 'timeToTender/deleteTimeToTender/',

  FETCH_TIME_USED: 'timeUsed/getAllTimeUsed',
  ADD_TIME_USED: 'timeUsed/addTimeUsed',
  UPDATE_TIME_USED: 'timeUsed/updateTimeUsed/',
  DELETE_TIME_USED: 'timeUsed/deleteTimeUsed/',

  FETCH_WORKING_DAYS: 'workingDays/getAllWorkingDays',
  ADD_WORKING_DAYS: 'workingDays/addWorkingDays',
  UPDATE_WORKING_DAYS: 'workingDays/updateWorkingDays/',
  DELETE_WORKING_DAYS: 'workingDays/deleteWorkingDays/',

  FETCH_DELAY_TYPES: 'delayType/getAllDelayType',
  ADD_DELAY_TYPES: 'delayType/addDelayType',
  UPDATE_DELAY_TYPES: 'delayType/UPDATE_DELAY_TYPES/',
  DELETE_DELAY_TYPES: 'delayType/deleteDelayType/',

  ADD_DELAY_REASON: 'delayReason/addDelayReason',
  FETCH_DELAY_REASON: 'delayReason/getAllDelayReason',
  UPDATE_DELAY_REASON: 'delayReason/updateDelayReason/',
  DELETE_DELAY_REASON: 'delayReason/deleteDelayReason/',

  FETCH_EXCHANGE_RATE: 'exchangeRate/getAllExchangeRate',
  ADD_EXCHANGE_RATE: 'exchangeRate/addExchangeRate',
  UPDATE_EXCHANGE_RATE: 'exchangeRate/updateExchangeRate/',
  DELETE_EXCHANGE_RATE: 'exchangeRate/deleteExchangeRate/',

  ADD_CURRENCY_TYPE: 'currencyType/addCurrencyType',
  FETCH_CURRENCY_TYPE: 'currencyType/getAllCurrencyType',
  UPDATE_CURRENCY_TYPE: 'currencyType/updateCurrencyType/',
  DELETE_CURRENCY_TYPE: 'currencyType/deleteCurrencyType/',

  ADD_FUEL_TYPE: 'fuelType/addFuelType',
  FETCH_FUEL_TYPE: 'fuelType/getAllFuelType',
  UPDATE_FUEL_TYPE: 'fuelType/updateFuelType/',
  DELETE_FUEL_TYPE: 'fuelType/deleteFuelType/',

  ADD_VESSEL_TYPE: 'vesselType/addVesselType',
  FETCH_VESSEL_TYPE: 'vesselType/getAllVesselType',
  UPDATE_VESSEL_TYPE: 'vesselType/updateVesselType/',
  DELETE_VESSEL_TYPE: 'vesselType/deleteVesselType/',

  GET_VESSEL_FUELCONSUMPTION_BY_VESSEL_ID:
    'vesselFuelConsumption/getVesselFuelConsumptionByVesselId/',
  UPDATE_VESSEL_FUEL_CONSUMPTION: 'vesselFuelConsumption/updateVesselFuelConsumption/',

  GET_VESSEL_SPEED_CONSUMPTION_BY_VESSEL_ID:
    'vesselSpeedConsumption/getVesselSpeedConsumptionByVesselId/',
  ADD_VESSEL_SPEED_CONSUMPTION: 'vesselSpeedConsumption/addVesselSpeedConsumption',
  UPDATE_VESSEL_SPEED_CONSUMPTION: 'vesselSpeedConsumption/updateVesselSpeedConsumption/',

  ADD_ECA_ZONE: 'ecaZone/addECAZone',
  FETCH_ECA_ZONE: 'ecaZone/getAllECAZone',
  UPDATE_ECA_ZONE: 'ecaZone/updateECAZone/',
  DELETE_ECA_ZONE: 'ecaZone/deleteECAZone/',

  ADD_PIRACY_ZONE: 'piracyZone/addPiracyZone',
  FETCH_PIRACY_ZONE: 'piracyZone/getAllPiracyZone',
  UPDATE_PIRACY_ZONE: 'piracyZone/updatePiracyZone/',
  DELETE_PIRACY_ZONE: 'piracyZone/deletePiracyZone/',

  ADD_USER_DEFINED_FUNCTION: 'udf/addUdf',
  FETCH_USER_DEFINED_FUNCTION: 'udf/getAllUdf',
  UPDATE_USER_DEFINED_FUNCTION: 'udf/updateUdf/',
  DELETE_USER_DEFINED_FUNCTION: 'udf/deleteUdf/',

  ADD_UDF_VALUES: 'udfValues/addUdfValues',
  FETCH_UDF_VALUES: 'udfValues/getAllUdfValues',
  UPDATE_UDF_VALUES: 'udfValues/updateUdfValues/',
  DELETE_UDF_VALUES: 'udfValues/deleteUdfValues/',

  ADD_FUEL_ZONE_SET: 'fuelZoneSet/addFuelZoneSet',
  FETCH_FUEL_ZONE_SET: 'fuelZoneSet/getAllFuelZoneSet',
  UPDATE_FUEL_ZONE_SET: 'fuelZoneSet/updateFuelZoneSet/',
  DELETE_FUEL_ZONE_SET: 'fuelZoneSet/deleteFuelZoneSet/',

  ADD_FUEL_ZONE_SET_DETAILS: 'fuelZoneSetDetails/addFuelZoneSetDetails',
  FETCH_FUEL_ZONE_SET_DETAILS: 'fuelZoneSetDetails/getAllFuelZoneSetDetails',
  UPDATE_FUEL_ZONE_SET_DETAILS: 'fuelZoneSetDetails/updateFuelZoneSetDetails/',
  DELETE_FUEL_ZONE_SET_DETAILS: 'fuelZoneSetDetails/deleteFuelZoneSetDetails/',

  ADD_FUEL_CONSUMPTION_CAT: 'fuelConsumptionCategory/addFuelConsumptionCategory',
  FETCH_FUEL_CONSUMPTION_CAT: 'fuelConsumptionCategory/getAllFuelConsumptionCategory',
  FETCH_FUEL_CONSUMPTION_CAT_BY_ID: 'fuelConsumptionCategory/getFuelConsumptionCategoryById/',
  FETCH_FUEL_CONSUMPTION_CAT_BY_VESSELTYPE_ID:
    'fuelConsumptionCategory/getFuelConsumptionCategoryByVesselTypeId/',
  UPDATE_FUEL_CONSUMPTION_CAT: 'fuelConsumptionCategory/updateFuelConsumptionCategory/',
  DELETE_FUEL_CONSUMPTION_CAT: 'fuelConsumptionCategory/deleteFuelConsumptionCategory/',
  GET_ALL_VESSEL_TYPE_DROPDOWN:'vesselType/getAllVesselTypeDropdown/',


  ADD_VESSEL_FUEL_CONSUMPTION: 'vesselFuelConsumption/addVesselFuelConsumption',

  ADD_PORT_ACTION_TYPE: 'portActiontype/addPortActionType',
  FETCH_PORT_ACTION_TYPE: 'portActiontype/getAllPortActionType',
  UPDATE_PORT_ACTION_TYPE: 'portActiontype/updatePortActionType/',
  DELETE_PORT_ACTION_TYPE: 'portActiontype/deletePortActionType/',

  ADD_PORT_FUNCTION: 'portFunction/addPortFunction',
  FETCH_PORT_FUNCTION: 'portFunction/getAllPortFunction',
  UPDATE_PORT_FUNCTION: 'portFunction/updatePortFunction/',
  DELETE_PORT_FUNCTION: 'portFunction/deletePortFunction/',

  ADD_PORT_ACTIVITY: 'portActivity/addPortActivity',
  FETCH_PORT_ACTIVITY: 'portActivity/getAllPortActivity',
  UPDATE_PORT_ACTIVITY: 'PortActivity/updatePortActivity/',
  DELETE_PORT_ACTIVITY: 'portActivity/deletePortActivity/',

  ADD_PORT_TYPE: 'portType/addPortType',
  FETCH_PORT_TYPE: 'portType/getAllPortType',
  UPDATE_PORT_TYPE: 'portType/updatePortType/',
  DELETE_PORT_TYPE: 'portType/deletePortType/',

  ADD_PORT_F_TO_ACTIVITIES: 'portFunctionToActivity/addPortFunctionToActivity',
  FETCH_PORT_F_TO_ACTIVITIES: 'portFunctionToActivity/getAllPortFunctionToActivity',
  UPDATE_PORT_F_TO_ACTIVITIES: 'portFunctionToActivity/updatePortFunctionToActivity/',
  DELETE_PORT_F_TO_ACTIVITIES: 'portFunctionToActivity/deletePortFunctionToActivity/',

  ADD_PORT: 'port/addPort',
  FETCH_PORT: 'port/getAllPort',
  UPDATE_PORT: 'port/updatePort/',
  DELETE_PORT: 'port/deletePort/',

  ADD_PORT_BERTH: 'portBerth/addPortBerth',
  FETCH_PORT_BERTH: 'portBerth/getAllPortBerth',
  UPDATE_PORT_BERTH: 'portBerth/updatePortBerth/',
  DELETE_PORT_BERTH: 'portBerth/deletePortBerth/',

  ADD_UOM: 'uom/addUom',
  FETCH_UOM: 'uom/getAllUom',
  UPDATE_UOM: 'uom/updateUom/',
  DELETE_UOM: 'uom/deleteUom/',
  GET_ALL_UOM_DROPDOWN: 'uom/getAllUomDropdown',
  ADD_CARGO: 'cargo/addCargo',
  FETCH_CARGO: 'cargo/getAllCargo',
  // UPDATE_CARGO: 'cargo/editCargo/',
  // DELETE_CARGO: 'cargo/',
  // ADD_CARGO_GROUP: 'cargoGroup/addCargoGroup',
  FETCH_CARGO_GROUP: 'cargoGroup/getAllCargoGroup',
  UPDATE_CARGO: 'cargo/updateCargo/',
  DELETE_CARGO: 'cargo/deleteCargo/',
  // FETCH_CARGO_GROUP: 'cargo/all',
  GET_CARGO_BY_ID: 'cargo/getCargoById/',

  ADD_CARGO_GROUP: 'cargoGroup/addCargoGroup',
  DELETE_CARGO_GROUP: 'cargoGroup/deleteCargoGroup/',
  UPDATE_CARGO_GROUP: 'cargoGroup/updateCargoGroup/',
  GET_ALL_CARGO_GROUP: 'cargoGroup/getAllCargoGroup',
  GET_ALL_CARGO_GROUP_DROPDOWN: 'cargoGroup/getAllCargoGroupDropDown',

  ADD_ADDRESS_BOOK: 'addressBook/addAddressBook',
  FETCH_ADDRESS_BOOK: 'addressBook/getAllAddressBook',
  FETCH_ADDRESS_BOOK_BY_TYPE: 'addressBook/getAllAddressBookByTypeDropdown?addressBookTypeId=',
  UPDATE_ADDRESS_BOOK: 'addressBook/updateAddressBook/',
  DELETE_ADDRESS_BOOK: 'addressBook/deleteAddressBook/',

  ADD_ADDRESS_TYPE: 'addressBookType/addAddressBook',
  FETCH_ADDRESS_TYPE: 'addressBookType/getAllAddressBookType',

  ADD_ACCOUNT_MASTER: 'accountMaster/addAccountMaster',
  FETCH_ACCOUNT_MASTER: 'accountMaster/getAllAccountMaster',
  UPDATE_ACCOUNT_MASTER: '',
  DELETE_ACCOUNT_MASTER: 'accountMaster/deleteAccountMaster/',

  ADD_VESSEL: 'vessel/addVesselTran',
  FETCH_VESSEL: 'vessel/getAllVessel',
  UPDATE_VESSEL: 'vessel/updateVesselTran/',
  DELETE_VESSEL: 'vessel/deleteVessel/',
  GET_VESSEL_TYPE_BY_ID: 'vesselType/getVesselTypeById/',

  ADD_BEAUT_FOR_SCALE: 'beaufortScale/addBeaufortScale',
  FETCH_BEAUT_FOR_SCALE: 'beaufortScale/getAllBeaufortScale',
  UPDATE_BEAUT_FOR_SCALE: 'beaufortScale/updateBeaufortScale/',
  DELETE_BEAUT_FOR_SCALE: 'beaufortScale/deleteBeaufortScale/',

  ADD_SEA_STATES: 'seaStates/addSeaStates',
  FETCH_SEA_STATES: 'seaStates/getAllSeaStates',
  UPDATE_SEA_STATES: 'seaStates/updateSeaStates/',
  DELETE_SEA_STATES: 'seaStates/deleteSeaStates/',

  ADD_SEA_SWELLS: 'seaSwells/addSeaSwells',
  FETCH_SEA_SWELLS: 'seaSwells/getAllSeaSwells',
  UPDATE_SEA_SWELLS: 'seaSwells/updateSeaSwells/',
  DELETE_SEA_SWELLS: 'seaSwells/deleteSeaSwells/',

  FETCH_LOADLINE_ZONE_SEASONS: 'loadlineZoneSeasons/getAllLoadlineZoneSeasons',
  ADD_LOADLINE_ZONE_SEASON: 'loadlineZoneSeasons/addLoadlineZoneSeasons',
  UPDATE_LOADLINE_ZONE_SEASON: 'loadlineZoneSeasons/updateLoadlineZoneSeasons/',
  DELETE_LOADLINE_ZONE_SEASON: 'loadlineZoneSeasons/deleteLoadlineZoneSeasons/',

  //  ADD_CONTACT:'addressBookContact/addAddressBookContact',
  //  FETCH_CONTACT:'addressBookContact/getAllAddressBookContact',
  //  UPDATE_CONTACT:'',
  //  DELETE_CONTACT:'addressBookContact/deleteAddressBookContact/',

  //  ADD_REMITTANCE:'addressBookRemitanceInfo/addAddressBookRemitanceInfo',
  FETCH_ADDRESS_BOOK_BANK_DETAILS: 'addressBookBankDetails/getAllAddressBookBankDetails',
  //  UPDATE_REMITTANCE:'',
  //  DELETE_REMITTANCE:'addressBookBankDetails/deleteAddressBookBankDetails/',

  //  ADD_PORT_SERVICE:'addressBookPorts/addAddressBookPorts',
  //  FETCH_PORT_SERVICE:'addressBookPorts/getAllAddressBookPorts',
  // UPDATE_PORT_SERVICE:'',
  // DELETE_PORT_SERVICE:'addressBookPorts/deleteAddressBookPorts/',

  FETCH_TCOUTLIST: 'tcOut/getAllTcOut',
  FETCH_TCINLIST: 'tcIn/getAllTcIn',
  FETCH_CONTRACT_TYPE: 'contractType/getAllcontractType',
  FETCH_TRADE_AREA: 'tradeArea/getAllTradeArea',
  FETCH_ALL_STATUS: 'status/getAllStatus',
  FETCH_BILLING_PERIOD: 'billPeriod/getAllBillPeriod',
  FETCH_BILLING_SCHEDULE: 'billSchedule/getAllBillSchedule',

  ADD_NEW_USER_SECURITY: 'user/addUser',
  GET_ALL_USER_DATA: 'user/getAllUser',
  DELETE_USER_BY_ID: 'user/deleteUser/',
  GET_USER_BY_ID: 'user/getUserById/',
  UPDATE_USER_BY_ID: 'user/editUser/',

  GET_LIST_MODULE_SUB_MODULE: 'module/getListModuleSubModule',
  ADD_NEW_MODULE: 'module/addModule',
  DELETE_MODULE_ID: 'module/deleteModule/',
  GET_MODULE_BY_ID: 'module/getModuleById/',
  UPDATE_MODULE_BY_ID: 'module/updateModule/',

  GET_LIST_GROUP: 'group/getAllGroupDropdown',
  ADD_NEW_GROUP: 'group/addGroup',
  GET_ALL_GROUP: 'group/getAllGroup',
  DEL_GROUP_DATA: 'group/deleteGroup/',
  GET_GROUP_BY_ID: 'group/getGroupById/',
  UPDATE_GROUP_BY_ID: 'group/updateGroup/',

  TOKEN_VALIDITY: 'user/checkTokenValidity',
  USER_LOGIN: 'user/login',
  FETCH_MODULETREE_BY_USER: 'module/getAllModulesByUserId/',
  FETCH_ALL_DROPDOWN: 'department/getAllDepartmentDropdown',

  EXCEL_EXPORT_FUELTYPE: 'excell/getExcelFuelType',
  EXCEL_EXPORT_ECAFUELZONE: 'excell/getExcelEcaFuelZone',
  EXCEL_EXPORT_FUELZONESET: 'excell/getExcelfuelZoneSet',
  EXCEL_EXPORT_VESSELTYPE: 'excell/getExcelVesselTyype',
  EXCEL_EXPORT_FUELCONSUMPTIONCATEGORY: 'excell/getExcelFuelConsumptionCategory',
  EXCEL_EXPORT_CHARTERPARTYFORM: 'excell/getExcelCharterPartyform',
  EXCEL_EXPORT_EXTRAFREIGHTTERM: 'excell/getExcelExtraFreightTerm',
  EXCEL_EXPORT_LAYTIMETOCOMMENCE: 'excell/getExcelLaytimeToCommence',
  EXCEL_EXPORT_LAYTIMETERMS: 'excell/getExcelLaytimeTerms',
  EXCEL_EXPORT_LAYTIMETYPES: 'excell/getLaytimeType',
  EXCEL_EXPORT_LOADINGCOSTS: 'excell/getExcelLoadingCosts',
  EXCEL_EXPORT_NORTOTENDER: 'excell/getExcelNorToTender',
  EXCEL_EXPORT_OTHERLOADINGTERMS: 'excell/getExcelOtherLoadingTerms',
  EXCEL_EXPORT_PAYMENTTERMS: 'excell/getExcelPaymentTerms',
  EXCEL_EXPORT_SHIFTINGTERMS: 'excell/getExcelShiftingTerms',
  EXCEL_EXPORT_STANDARDPARAGRAPHS: 'excell/getExcelStandardParagraphs',
  EXCEL_EXPORT_TIMETOTENDER: 'excell/getExcelTimeToTender',
  EXCEL_EXPORT_TIMEUSED: 'excell/getExcelTimeUsed',
  EXCEL_EXPORT_WORKINGDAYS: 'excell/getExcelWorkingDays',
  EXCEL_EXPORT_DELAYREASON: 'excell/getExcelDelayReason',
  EXCEL_EXPORT_DELAYTYPE: 'excell/getExcelDelayType',
  EXCEL_EXPORT_CURRENCYTYPES: 'excell/getExcelCurrencyTypes',
  EXCEL_EXPORT_EXCHANGERATE: 'excell/getExcelExchangerate',
  EXCEL_EXPORT_LOADLINEZONESEASON: 'excell/getExcelLoadlineZoneSeason',
  EXCEL_EXPORT_PORTACTIVITY: 'excell/getExcelPortActivity',
  EXCEL_EXPORT_PORTFUNCTIONS: 'excell/getExcelPortFunction',
  EXCEL_EXPORT_PORTACTIONTYPE: 'excell/getExcelPortActionType',
  EXCEL_EXPORT_PORTFUNCTIONTOACTIVITY: 'excell/getExcelPortFuctionToActivities',
  EXCEL_EXPORT_PORTTYPE: 'excell/getExcelPortType',
  EXCEL_EXPORT_ADDRESSBOOK: 'excell/getExcelAddressBook',
  EXCEL_EXPORT_PORT: 'excell/getExcelPort',
  EXCEL_EXPORT_CARGONAMES: 'excell/getCargoNames',
  EXCEL_EXPORT_CARGOGROUP: 'excell/getCargoGroup',
  EXCEL_EXPORT_VESSEL: 'excell/getVessel',
  EXCEL_EXPORT_WORKSHEET:'excell/getExcelWorksheet',

  FETCH_TOLERANCE_TYPES: 'toleranceType/getAllToleranceType',
  FETCH_EXPENSE_HEAD_BY_TYPE: 'miscIncomeExpenseHead/getMiscIncomeExpenseHeadByType/',

  FETCH_ALL_MAIL_CATEGORY: 'mailCategory/getAllMailCategory',
  ADD_MAIL_CATEGORY: 'mailCategory/addMailCategory',
  GET_MAIL_CATEGORY_BY_ID: 'mailCategory/getMailCategoryById/',
  GET_MAIL_CATEGORY_BY_ID: 'mailCategory/getMailCategoryById/',
  UPDATE_MAIL_CATEGORY: 'mailCategory/updateMailCategory/',
  DELETE_MAIL_CATEGORY: 'mailCategory/deleteMailCategory/',
}

export const QueryConst = {
  ALL_ESTIMATE : 'Allestimate',
  DELAY_REASON: 'Delayreason',
  DELAY_TYPES: 'Delaytypes',
  CURRENCY_TYPE: 'Currencytype',
  EXCHANGE_RATE: 'Exchangerate',
  LOADLINE_ZONE_SEASONS: 'Loadlinezoneseasons',
  COUNTRY: 'Country',

  ALL_SEASTATES: 'Seastates',
  ALL_GROUP :'AllGroups',
  ALL_MODULES:'ModuleList',
  ALL_USERLIST :'UserList',
  ALL_BEAUFORT:'Beaufort',
  ALL_SEASWELLS:'SeaSwells',
  ALL_UNITOFMEASURE:'UnitOfMeasure',
  ALL_USER_DEFINED :'UserDefinedFields',
  ALL_ECA_FUELZONES :'ECAFuelZone',
  ALL_FUELCONSUMPTION_CATEGORY:'FuelConsumptionCat',
  ALL_FUEL_LUBE_TYPE:'FuelType',
  ALL_FUELZONE_SETS :'FuelZoneSet',
  ALL_VESSELTYPE:'VesselType',
  AllStates:'AllStates',
  AllPortActionType: 'AllPortActionType',
  AllPortActivity: 'AllPortActivity',
  AllPortFunction: 'AllPortFunction',
  PortFToActivities:'PortFToActivities',
  PortType:'PortType',
  ALL_ORGANISATION:"AllOrganisation",
  ALL_WORKSHEETS:"AllWorksheets",
  ALL_ADDRESS_BOOK:"AllAddressBook",
  ALL_CARGO_GROUP:'AllCargoGroup',
  ALL_CARGO:"AllCargo",
  ALL_PORT:'AllPort',
  ALL_VESSEL: "AllVessel",
  ALL_CHARTER_PARTY: 'AllCharterParty',
  ALL_EXTRA_FREIGHT: 'AllExtraFreight',
  ALL_LAYTIME_TERM: 'LaytimeTerm',
  ALL_LAYTIME_COMMENCE: 'AllLaytimeCommence',
  ALL_LAYTIME_TYPE: 'LaytimeType',
  ALL_LOADING_COSTS: "LoadingCosts",
  ALL_NOR_TO_TENDER: 'NorToTender',
  ALL_OTHER_LOADING_TERM: 'OtherLoadingTerm',
  ALL_PAYMENT_TERM: 'PaymentTerm' ,
  ALL_SHIFTING_TERM: 'ShiftingTerm' ,
  ALL_STANDARD_PARAGRAPH: 'StandardParagraph' ,
  ALL_TIME_TO_TENDER: 'TimeToTender' ,
  ALL_TIME_USED: 'TimeUsed' ,
  ALL_WORKING_DAYS: 'WorkingDays' ,


}
